### ISSUE TITLE
Exempt a single player

### ISSUE THREAD

**Issue by zD12** [FearFree/WhoBannedMe#12]
Hello FearFish and developers!

I am an "executive" of a Minecraft server that allows all players to be operator ("OP") which, as you may foreshadow causes problems.  I saw your plugin is, 'GNU GENERAL PUBLIC LICENSE - Version 2' which allows myself to edit the plugin as I freely chose.

I modified the plugins.yml to NOT exempt operators, as for it exempts all players..
## 

 whobannedme.exempt:
description: Allows bypassing the ban check on login
default: false
## 

I am wounding if you'd have the ability to exempt players from a YML file, sure as exempted.yml or am I required to exempt inside the source..   If so, how?

I am thinking about:

{
if (pName.equalsIgnoreCase("player1"));
   exempt = true;
}
{
if (pName.equalsIgnoreCase("player2"));
   exempt = true;
}
{
if (pName.equalsIgnoreCase("player3"));
   exempt = true;
}
## 

Would that work, and is it possible for you to create a 'exempted.yml'

**Comment by LordRalex** [comment]
It is permission based, so that means just use your permissions plugin and grant them that exempt permission. There is no file needed to do that.

**Comment by zD12** [comment]
I do not use a permissions plugin (GroupManager, nor PremissionsEX) and I'd truly do not wish to install one.   At the moment I use a modified version of TotalFreedomMod, https://github.com/TotalFreedom/TotalFreedomMod/ which is the closest plugin to 'Premissions'

**Comment by zD12** [comment]
I guess that eliminates the factor of adding another file, may you instead 'teach' me how to exempt a player within the source?

**Comment by LordRalex** [comment]
You can either do it with if statements and hardcode their UUID into the plugin, or read it from a file and check against that on logins.

**Comment by zD12** [comment]
OK.
